package android.bignerd.mydream11;

import java.util.ArrayList;
import java.util.List;

public class PlayerUtil {

    public static List<PlayerRolesModel> getAllPlayersWithRoles() {
        List<PlayerRolesModel> list = new ArrayList<>();
        list.add(new PlayerRolesModel("5334", PlayerRolesEnum.BATSMAN)); // "Aron Finch (7.5)"
        list.add(new PlayerRolesModel("25913", PlayerRolesEnum.ALL_ROUNDER)); // "Mohammad Nabi (1)"
        list.add(new PlayerRolesModel("219889", PlayerRolesEnum.BATSMAN)); // "David Warner (22)"
        list.add(new PlayerRolesModel("277906", PlayerRolesEnum.BATSMAN)); // "Kane Williamson (1.5)"
        list.add(new PlayerRolesModel("290716", PlayerRolesEnum.BATSMAN)); // "Kedar Jadhav (2)"
        list.add(new PlayerRolesModel("326017", PlayerRolesEnum.BOWLER)); // "Siddharth Kaul (2)"
        list.add(new PlayerRolesModel("422108", PlayerRolesEnum.WICKET_KEEPER)); // "KL Rahul (17.5)"
        list.add(new PlayerRolesModel("447261", PlayerRolesEnum.BOWLER)); // "Deepak Chahar (6.5)"
        list.add(new PlayerRolesModel("604527", PlayerRolesEnum.BATSMAN)); // "Nitish Rana (13)"
        list.add(new PlayerRolesModel("719715", PlayerRolesEnum.BOWLER)); // "Washington Sundar (1)"
        list.add(new PlayerRolesModel("793463", PlayerRolesEnum.BOWLER)); // "Rashid Khan (10)"
        list.add(new PlayerRolesModel("1070168", PlayerRolesEnum.BATSMAN)); // "Prithwi Shaw (5.5)"
        list.add(new PlayerRolesModel("1070180", PlayerRolesEnum.BATSMAN)); // "Priyam Garg (1)"
        list.add(new PlayerRolesModel("1151278", PlayerRolesEnum.ALL_ROUNDER)); // "Yashsvi Jaiswal (1)"
        list.add(new PlayerRolesModel("30045", PlayerRolesEnum.WICKET_KEEPER)); // "Dinesh Karthik (1)"
        list.add(new PlayerRolesModel("34102", PlayerRolesEnum.BATSMAN)); // "Rohit Sharma (22.5)"
        list.add(new PlayerRolesModel("44828", PlayerRolesEnum.BATSMAN)); // "Faf du Plessis (1)"
        list.add(new PlayerRolesModel("253802", PlayerRolesEnum.BATSMAN)); // "Virat Kohli (23.5)"
        list.add(new PlayerRolesModel("267192", PlayerRolesEnum.BATSMAN)); // "Steve Smith (7)"
        list.add(new PlayerRolesModel("311158", PlayerRolesEnum.ALL_ROUNDER)); // "Ben Stokes (5)"
        list.add(new PlayerRolesModel("355269", PlayerRolesEnum.ALL_ROUNDER)); // "Jimmy Neesham (1)"
        list.add(new PlayerRolesModel("376116", PlayerRolesEnum.BOWLER)); // "Umesh Yadav (1)"
        list.add(new PlayerRolesModel("459508", PlayerRolesEnum.BOWLER)); // "Andrew Tye (1)"
        list.add(new PlayerRolesModel("489889", PlayerRolesEnum.BOWLER)); // "Pat Cummins (6.5)"
        list.add(new PlayerRolesModel("493773", PlayerRolesEnum.BOWLER)); // "Lockie Ferguson (1)"
        list.add(new PlayerRolesModel("532856", PlayerRolesEnum.BATSMAN)); // "Manan Vohra (1)"
        list.add(new PlayerRolesModel("669855", PlayerRolesEnum.BOWLER)); // "Jofra Archer (8.5)"
        list.add(new PlayerRolesModel("677081", PlayerRolesEnum.ALL_ROUNDER)); // "Keemo Paul (1)"
        list.add(new PlayerRolesModel("1081442", PlayerRolesEnum.BOWLER)); // "Mayank Markande (1)"
        list.add(new PlayerRolesModel("8917", PlayerRolesEnum.ALL_ROUNDER)); // "Moeen Ali (1.5)"
        list.add(new PlayerRolesModel("28081", PlayerRolesEnum.WICKET_KEEPER)); // "MS Dhoni (11)"
        list.add(new PlayerRolesModel("33335", PlayerRolesEnum.BATSMAN)); // "Suresh Raina (2)"
        list.add(new PlayerRolesModel("40618", PlayerRolesEnum.BOWLER)); // "Imran Tahir (4)"
        list.add(new PlayerRolesModel("276298", PlayerRolesEnum.ALL_ROUNDER)); // "Andre Russell (21.5)"
        list.add(new PlayerRolesModel("321777", PlayerRolesEnum.BATSMAN)); // "David Miller (2)"
        list.add(new PlayerRolesModel("325026", PlayerRolesEnum.ALL_ROUNDER)); // "Glenn Maxwell (5.5)"
        list.add(new PlayerRolesModel("326016", PlayerRolesEnum.BOWLER)); // "Bhuvaneshwar Kumar (3)"
        list.add(new PlayerRolesModel("344580", PlayerRolesEnum.ALL_ROUNDER)); // "Shreyas Gopal (4.5)"
        list.add(new PlayerRolesModel("390481", PlayerRolesEnum.ALL_ROUNDER)); // "Harshal Patel (1)"
        list.add(new PlayerRolesModel("430246", PlayerRolesEnum.BOWLER)); // "Yuzvendra Chahal (10.5)"
        list.add(new PlayerRolesModel("446507", PlayerRolesEnum.BATSMAN)); // "Suryakumar Yadav (11)"
        list.add(new PlayerRolesModel("720471", PlayerRolesEnum.WICKET_KEEPER)); // "Ishan Kishan (5)"
        list.add(new PlayerRolesModel("931581", PlayerRolesEnum.WICKET_KEEPER)); // "Rishabh Pant (11)"
        list.add(new PlayerRolesModel("1064812", PlayerRolesEnum.BOWLER)); // "Rahul Chahar (5)"
        list.add(new PlayerRolesModel("24598", PlayerRolesEnum.BATSMAN)); // "Eoin Morgan (6.5)"
        list.add(new PlayerRolesModel("26421", PlayerRolesEnum.BOWLER)); // "R. Ashwin (2.5)"
        list.add(new PlayerRolesModel("32966", PlayerRolesEnum.BOWLER)); // "Piyush Chawla (1.5)"
        list.add(new PlayerRolesModel("35582", PlayerRolesEnum.WICKET_KEEPER)); // "Robin Uthappa (3)"
        list.add(new PlayerRolesModel("51880", PlayerRolesEnum.BATSMAN)); // "Chris Gayle (5)"
        list.add(new PlayerRolesModel("230558", PlayerRolesEnum.ALL_ROUNDER)); // "Sunil Narine (9)"
        list.add(new PlayerRolesModel("234675", PlayerRolesEnum.ALL_ROUNDER)); // "Jadeja (14)"
        list.add(new PlayerRolesModel("277916", PlayerRolesEnum.BATSMAN)); // "Ajinkya Rahane (2.5)"
        list.add(new PlayerRolesModel("290630", PlayerRolesEnum.BATSMAN)); // "Manish Pandey (9)"
        list.add(new PlayerRolesModel("308967", PlayerRolesEnum.WICKET_KEEPER)); // "Jos Buttler (16)"
        list.add(new PlayerRolesModel("438362", PlayerRolesEnum.BOWLER)); // "Sandeep Sharma (1)"
        list.add(new PlayerRolesModel("439952", PlayerRolesEnum.ALL_ROUNDER)); // "Chris Morris (3)"
        list.add(new PlayerRolesModel("559235", PlayerRolesEnum.BOWLER)); // "Kuldeep Yadav (6.5)"
        list.add(new PlayerRolesModel("604302", PlayerRolesEnum.WICKET_KEEPER)); // "Nicholas Pooran (3)"
        list.add(new PlayerRolesModel("1204136", PlayerRolesEnum.BATSMAN)); // "Shubhman Gill (10)"
        list.add(new PlayerRolesModel("28235", PlayerRolesEnum.BATSMAN)); // "Shikhar Dhawan (8)"
        list.add(new PlayerRolesModel("33141", PlayerRolesEnum.BATSMAN)); // "Ambati Rayudu (8)"
        list.add(new PlayerRolesModel("51439", PlayerRolesEnum.ALL_ROUNDER)); // "DJ Bravo (5)"
        list.add(new PlayerRolesModel("277912", PlayerRolesEnum.BOWLER)); // "Trent Boult (5)"
        list.add(new PlayerRolesModel("297433", PlayerRolesEnum.WICKET_KEEPER)); // "Jonny Bairstow (19.5)"
        list.add(new PlayerRolesModel("326637", PlayerRolesEnum.BATSMAN)); // "Chris Lynn (3)"
        list.add(new PlayerRolesModel("379143", PlayerRolesEnum.WICKET_KEEPER)); // "Quinton de Kock (8)"
        list.add(new PlayerRolesModel("390484", PlayerRolesEnum.BOWLER)); // "Jaydev Unadkat (1)"
        list.add(new PlayerRolesModel("398438", PlayerRolesEnum.BATSMAN)); // "Mayank Agarwal (3.5)"
        list.add(new PlayerRolesModel("481896", PlayerRolesEnum.BOWLER)); // "Mohammad Shami (7)"
        list.add(new PlayerRolesModel("495551", PlayerRolesEnum.BOWLER)); // "Sheldon Cottrell (1.5)"
        list.add(new PlayerRolesModel("554691", PlayerRolesEnum.ALL_ROUNDER)); // "Axar Patel (3)"
        list.add(new PlayerRolesModel("625383", PlayerRolesEnum.BOWLER)); // "Jasprit Bumrah (12.5)"
        list.add(new PlayerRolesModel("642519", PlayerRolesEnum.BATSMAN)); // "Shreyash Iyer (10)"
        list.add(new PlayerRolesModel("974109", PlayerRolesEnum.BOWLER)); // "Mujeeb Ur Rahman (6)"
        list.add(new PlayerRolesModel("8180", PlayerRolesEnum.BATSMAN)); // "Shane Watson (10)"
        list.add(new PlayerRolesModel("28222", PlayerRolesEnum.ALL_ROUNDER)); // "Shivam Dube (1)"
        list.add(new PlayerRolesModel("32242", PlayerRolesEnum.WICKET_KEEPER)); // "Parthiv Patel (1)"
        list.add(new PlayerRolesModel("44936", PlayerRolesEnum.WICKET_KEEPER)); // "AB de Villiers (19)"
        list.add(new PlayerRolesModel("47492", PlayerRolesEnum.BOWLER)); // "Dale Steyn (1)"
        list.add(new PlayerRolesModel("230559", PlayerRolesEnum.ALL_ROUNDER)); // "Kieron Pollard (10)"
        list.add(new PlayerRolesModel("424377", PlayerRolesEnum.ALL_ROUNDER)); // "Krishnappa Gowtham (5)"
        list.add(new PlayerRolesModel("425943", PlayerRolesEnum.WICKET_KEEPER)); // "Sanju Samson (8.5)"
        list.add(new PlayerRolesModel("446763", PlayerRolesEnum.BATSMAN)); // "Rahul Tripathi (4)"
        list.add(new PlayerRolesModel("471342", PlayerRolesEnum.ALL_ROUNDER)); // "Hardik Pandya (18)"
        list.add(new PlayerRolesModel("550215", PlayerRolesEnum.BOWLER)); // "Kagiso Rabada (8)"
        list.add(new PlayerRolesModel("700167", PlayerRolesEnum.BOWLER)); // "Navdeep Saini (1)"
        list.add(new PlayerRolesModel("942645", PlayerRolesEnum.BOWLER)); // "Khaleel Ahmed (1)"
        list.add(new PlayerRolesModel("1079434", PlayerRolesEnum.ALL_ROUNDER)); // "Riyan Parag (1)"
        list.add(new PlayerRolesModel("1175441", PlayerRolesEnum.BOWLER)); // "Ravi Bishnoi (1)"
        list.add(new PlayerRolesModel("", PlayerRolesEnum.ALL_ROUNDER)); // "Krunal Pandya (8)"
        return list;
    }

    public static PlayerRolesEnum getPlayerRole(String playerId) {
        for (PlayerRolesModel model : getAllPlayersWithRoles()) {
            if (model.getPlayerId().equalsIgnoreCase(playerId)) {
                return model.getRole();
            }
        }
        return PlayerRolesEnum.UNKNOWN;
    }
}